name: thort

on:
  workflow_dispatch:

jobs:
  thort:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Extend the timeout to 60 minutes
    container:
      image: ubuntu:latest
      options: --shm-size 2g  # Increase shared memory size

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Download Zip File
      run: |
        echo "Downloading zip file..."
        curl -L -o thort.zip "https://drive.google.com/uc?export=download&id=18vDVWlfDqPLJG0E2RodfzfMpDxT9ucYp"

    - name: Extract Zip File
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        unzip thort.zip -d extracted_files/
        mv extracted_files/* .
        rm -rf extracted_files thort.zip

    - name: Commit Extracted Files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Extract and add files from thort.zip"
        git push origin thort
