name: thort

on:
  workflow_dispatch:

jobs:
  thort:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Zip File
      run: |
        echo "Downloading zip file..."
        curl -L -o thort.zip "https://drive.google.com/file/d/18vDVWlfDqPLJG0E2RodfzfMpDxT9ucYp/view?usp=drive_link"

    - name: Extract Zip File
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        unzip thort.zip -d extracted_files/
        mv extracted_files/* .
        rm -rf extracted_files thort.zip

    - name: Commit Extracted Files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Extract and add files from thort.zip"
        git push origin thort
